language: elixir

sudo: false

elixir:
  - 1.8

otp_release:
  - 22.0

script:
  - mix compile --warnings-as-errors
  - mix coveralls.html
  - mix credo --strict
  - mix format --check-formatted --dry-run
  - mix test