# This is a basic workflow to help you get started with Actions

name: Elixir CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  set_up:
    runs-on: ubuntu-18.04
    name: Set up
    strategy:
      matrix:
        os: [ubuntu-18.04]
        otp: [22.0]
        elixir: [1.9.0]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        otp-version: ${ matrix.otp }
        elixir-version: ${ matrix.elixir }

    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Compile
      run: |
        mix compile --warnings-as-errors

  analize_code:
    name: Analize Code
    needs: set_up
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
    - name: Format code
      run: mix format --check-formatted
        
    - name: credo
      run: mix credo --strict
      
    - name: dialyzir
        run: mix dialyzer --halt-exit-status --no-compile

  run_test:
    runs-on: ubuntu-18.04
    name: Run tests
    needs: analize_code
    steps:
    - name: Tests
      run: mix test
